### ISSUE TITLE
plugin doesn't seem to be need

### ISSUE THREAD

**Issue by jimblue** [elisherer/webpack-dev-server-waitpage#20]
While working with `webpack-dev-server-waitpage` I've notice that only the second step of the install method seems to be need.

After launching `webpack-dev-server` without `webpackDevServerWaitpage.plugin()` in the config the wait page still perfectly works.

But maybe I'm wrong? Could you explain why both are needed? 😄

**Comment by elisherer** [comment]
The problem is the order of events. if a plugin exists, it will hook on the progress earlier. That's because of when webpack dev server is running express (the before function of the devServer), it only happens after all the plugins were installed, meaning you don't have progress running, just the wait page stuck, and only getting the last section of the progress of ~95%.
I tested the new requirement on webpack 4.40+ and v5 (beta)

**Comment by jimblue** [comment]
Are you sure ? Because I don't have the same behaviour here.
I don't use the plugin but progress page progress still start around 10%... not 95%.
