### ISSUE TITLE
material theme style bug

### ISSUE THREAD

**Issue by jimblue** [elisherer/webpack-dev-server-waitpage#21]
I've notice 2 problems with material theme:
- The circular loader progress go in the wrong direction.
- The waitpage randomly flashes several time.

Because it's probably easier to understand here is a screen capture of the problem.

![screencapture](https://user-images.githubusercontent.com/10623367/92657753-a3f6ef00-f2f5-11ea-8f17-f2f94bc023bf.gif)

**Comment by jimblue** [comment]
Removing the plugin from the configuration (like sugested in #20) apparently fixe the flashes issue. Can you confirm?

**Comment by elisherer** [comment]
So that's kind of part of the feature. The flashes are full page refreshes because the wait page is waiting to load the actual page (and it doesn't use ajax).
The direction of the loader is just how I did it, if you have a suggestion of how to make it different, make a PR and I'll consider changing it.

About removing the plugin, I wrote on the other issue that no progress events come up, so indirectly you are causing the same page to appear causing no re-rendering of the page.

**Comment by jimblue** [comment]
ok I better understand now, thank you.

About the loader direction, I found it not very natural, maybe because 99% of all loader on the web spin left to right. Just check on codepen : https://codepen.io/search/pens?q=loader

And for waitpage flashes due to page refresh, I have no idea how to solve that for now, gonna think about it.
